/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class BillingSystem extends javax.swing.JFrame {

    String operations;
    String answers;
    double num1, num2, result;
    
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnPer = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        btnAllClear = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 650));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jPanel1.add(txtDisplay);
        txtDisplay.setBounds(30, 10, 270, 50);

        btn1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setPreferredSize(new java.awt.Dimension(60, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(30, 70, 60, 50);

        btn3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(60, 50));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(170, 70, 60, 50);

        btnAdd.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setPreferredSize(new java.awt.Dimension(60, 50));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(240, 70, 60, 50);

        btn2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setPreferredSize(new java.awt.Dimension(60, 50));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(100, 70, 60, 50);

        btn4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setPreferredSize(new java.awt.Dimension(60, 50));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(30, 130, 60, 50);

        btn5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setPreferredSize(new java.awt.Dimension(60, 50));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(100, 130, 60, 50);

        btn6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setPreferredSize(new java.awt.Dimension(60, 50));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(170, 130, 60, 50);

        btnMinus.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnMinus.setText("-");
        btnMinus.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinus);
        btnMinus.setBounds(240, 130, 60, 50);

        btn7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(60, 50));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(30, 190, 60, 50);

        btn8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setPreferredSize(new java.awt.Dimension(60, 50));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(100, 190, 60, 50);

        btn9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setPreferredSize(new java.awt.Dimension(60, 50));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(170, 190, 60, 50);

        btnMultiply.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiply);
        btnMultiply.setBounds(240, 190, 60, 50);

        btn0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.setPreferredSize(new java.awt.Dimension(60, 50));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);
        btn0.setBounds(30, 250, 60, 50);

        btnDivide.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivide);
        btnDivide.setBounds(240, 250, 60, 50);

        btnDot.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnDot.setText(".");
        btnDot.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        jPanel1.add(btnDot);
        btnDot.setBounds(100, 250, 60, 50);

        btnPer.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnPer.setText("%");
        btnPer.setPreferredSize(new java.awt.Dimension(60, 50));
        btnPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPer);
        btnPer.setBounds(170, 250, 60, 50);

        btnclear.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnclear.setText("CE");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(30, 310, 130, 40);

        btnAssign.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnAssign.setText("=");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        jPanel1.add(btnAssign);
        btnAssign.setBounds(170, 310, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 80, 330, 360);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(930, 370));
        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox1.setText("Pasta");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(30, 20, 140, 49);

        jCheckBox2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox2.setText("Vegges");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(30, 80, 140, 49);

        jCheckBox3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox3.setText("Pizza");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(30, 140, 140, 49);

        jCheckBox4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox4.setText("Waffers");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(30, 200, 150, 49);

        jCheckBox5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox5.setText("Juice");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(30, 260, 160, 49);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(190, 30, 80, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(190, 90, 80, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(190, 150, 80, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(190, 210, 80, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 270, 80, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Total number of Items");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 20, 340, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Total Delivery Cost");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 130, 300, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setText("Total Cost of Items");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 70, 330, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setText("CGST");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 210, 230, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setText("SGST");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 260, 230, 40);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(510, 30, 80, 30);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(510, 80, 80, 30);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(510, 140, 80, 30);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jPanel3.add(jTextField9);
        jTextField9.setBounds(510, 210, 80, 30);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jPanel3.add(jTextField10);
        jTextField10.setBounds(510, 260, 80, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(290, 20, 630, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(380, 70, 930, 370);

        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 110));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Sub Total");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(170, 10, 210, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Tax");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(170, 50, 150, 20);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setText("Total Amount");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(170, 90, 150, 20);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rs. 0.00");
        jPanel4.add(jTextField11);
        jTextField11.setBounds(480, 10, 310, 30);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs. 0.00");
        jPanel4.add(jTextField12);
        jTextField12.setBounds(480, 50, 310, 30);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs. 0.00");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField13);
        jTextField13.setBounds(480, 90, 310, 30);

        btnAllClear.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnAllClear.setText("Clear");
        btnAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllClearActionPerformed(evt);
            }
        });
        jPanel4.add(btnAllClear);
        btnAllClear.setBounds(870, 10, 310, 50);

        btnCal.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        jPanel4.add(btnCal);
        btnCal.setBounds(870, 70, 310, 50);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(40, 450, 1250, 130);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Online Billing System");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(490, 10, 380, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn1.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn2.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn0.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn3.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn4.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn5.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn6.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn7.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn8.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String EnterNumber = txtDisplay.getText() + btn9.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(!txtDisplay.getText().contains("."))
        {
            txtDisplay.setText(txtDisplay.getText() + btnDot.getText());
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        num1 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
         num1 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
         num1 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
         num1 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerActionPerformed
         num1 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "%";
    }//GEN-LAST:event_btnPerActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        num2 = Double.parseDouble(txtDisplay.getText());
        
        if(operations == "+")
        {
            result = num1 + num2;
            answers = String.format("%.2f", result);
            txtDisplay.setText(answers);
        }
        else  if(operations == "-")
        {
            result = num1 - num2;
            answers = String.format("%.2f", result);
            txtDisplay.setText(answers);
        }
        else  if(operations == "*")
        {
            result = num1 * num2;
            answers = String.format("%.2f", result);
            txtDisplay.setText(answers);
        }
        else  if(operations == "/")
        {
            result = num1 / num2;
            answers = String.format("%.2f", result);
            txtDisplay.setText(answers);
        }
        else  {
            result = num1 % num2;
            answers = String.format("%.2f", result);
            txtDisplay.setText(answers);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void btnAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllClearActionPerformed
        txtDisplay.setText("");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField7.setText("0");
        jTextField8.setText("0");
        jTextField9.setText("0");
        jTextField10.setText("0");
        jTextField11.setText("Rs. 0.00");
        jTextField12.setText("Rs. 0.00");
        jTextField13.setText("Rs. 0.00");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
    }//GEN-LAST:event_btnAllClearActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jTextField1.setEditable(true);
            jTextField1.setText("");
            jTextField1.requestFocus();
        }
        else
        {
            jTextField1.setEditable(false);
            jTextField1.setText("0");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         if(jCheckBox2.isSelected())
        {
            jTextField2.setEditable(true);
            jTextField2.setText("");
            jTextField2.requestFocus();
        }
        else
        {
            jTextField2.setEditable(false);
            jTextField2.setText("0");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if(jCheckBox3.isSelected())
        {
            jTextField3.setEditable(true);
            jTextField3.setText("");
            jTextField3.requestFocus();
        }
        else
        {
            jTextField3.setEditable(false);
            jTextField3.setText("0");
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
         if(jCheckBox4.isSelected())
        {
            jTextField4.setEditable(true);
            jTextField4.setText("");
            jTextField4.requestFocus();
        }
        else
        {
            jTextField4.setEditable(false);
            jTextField4.setText("0");
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if(jCheckBox5.isSelected())
        {
            jTextField5.setEditable(true);
            jTextField5.setText("");
            jTextField5.requestFocus();
        }
        else
        {
            jTextField5.setEditable(false);
            jTextField5.setText("0");
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        if ( jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() || jCheckBox5.isSelected() )
        {
            double pa = Double.parseDouble(jTextField1.getText()) * 60;
            double v = Double.parseDouble(jTextField2.getText()) * 50;
            double p = Double.parseDouble(jTextField3.getText()) * 49;
            double w = Double.parseDouble(jTextField4.getText()) * 35;
            double j = Double.parseDouble(jTextField5.getText()) * 30;
            
            int pa1 = Integer.parseInt(jTextField1.getText());
            int v1 =  Integer.parseInt(jTextField2.getText());
            int p1 = Integer.parseInt(jTextField3.getText());
            int w1 = Integer.parseInt(jTextField4.getText());
            int j1 = Integer.parseInt(jTextField5.getText());
            
            int tni = pa1 + v1 + p1 + w1 + j1;
            double tci = pa +v + p + w + j;
            double tdc = tci * 5 / 100;
            
            double subtotal = tci + tdc;
            double cgst = subtotal * 9 / 100;
            double sgst = cgst;
            
            double tax = cgst + sgst;
            double totalamount = subtotal + tax;
            
            
            jTextField6.setText(String.valueOf(tni));
            
            String tcosts = String.format("%.2f", tci);
            jTextField7.setText((String)tcosts);
            
            String dcost = String.format("%.2f", tdc);
            jTextField8.setText((String)dcost);
            
            String stotal = String.format("%.2f", subtotal);
            jTextField11.setText((String)stotal);
            
            String cst = String.format("%.2f", cgst);
            jTextField9.setText((String)cst);
            
            String sst = String.format("%.2f", sgst);
            jTextField10.setText((String)sst);
            
            String tx = String.format("%.2f", tax);
            jTextField12.setText((String)tx);
            
            String tamount = String.format("%.2f", totalamount);
            jTextField13.setText((String)tamount);
            
            
        } 
        else {
            JOptionPane.showMessageDialog(null,"Please enter a choice..!");
        }
    }//GEN-LAST:event_btnCalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAllClear;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPer;
    private javax.swing.JButton btnclear;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
